mysql:
  host: localhost
  port: 3306
  user: root
  pass: password
  db: man10
tax: 0
prize: 0.5
fee: 10000
autobet: 100000
newbiePlayableCount: 10
registerKDRLimit: 0.2

auto-running:
  enabled: true
  end-message: "&l今日はここまで！ また次回参加してくれ！"
  schedule:
    # SUN:1 ~ SUT:7
    # MODE: free, normal, allowlist, pro
    - 1
      WEEK: 7
      START: "18:00:00"
      END: "19:00:00"
      MODE: "free"
      STARTMESSAGE: "&b&l&nMFCの練習試合を開催します！ ぜひご参加ください！"
    - 2
      WEEK: 1
      START: "18:00:00"
      END: "20:00:00"
      MODE: "normal"
      STARTMESSAGE: "&c&l&kXXXXX &r&c&l&n今宵はMFCの決戦だ！ 集え！戦士たちよ！ &c&l&kXXXXX"