mysql:
  host: localhost
  port: 3306
  user: root
  pass: password
  db: man10
tax: 0
prize: 0.5
fee: 10000
autobet: 100000
newbiePlayableCount: 10
registerKDRLimit: 0.2

auto-running:
  enabled: true
  schedule:
    # SUN:1 ~ SUT:7
    # MODE: free, normal, allowlist, pro
    - 1
      WEEK: 7
      START: "18:00:00"
      END: "19:00:00"
      MODE: "free"
    - 2
      WEEK: 1
      START: "18:00:00"
      END: "20:00:00"
      MODE: "normal"